### PR TITLE
deprecate package

### PR DESCRIPTION
**Pull request by ajavadia**

### CODE REVIEW

**Comment by jwoehr** [comment]
This package builds on IBM i.
Full QISKit, enough to connect, does not.

**Comment by jwoehr** [comment]
We now have qiskit-terra building on IBM i

**Comment by ajavadia** [comment]
This package is superseded by https://github.com/Qiskit/qiskit-ibmq-provider

**Comment by msegado** [comment]
@pacomf / other maintainers: can someone please merge this to warn early adopters that the package is deprecated?

**Comment by msegado** [comment]
Thanks!

**Pull request merged**
